### PR TITLE
add basic 2FA support (chipTAN)

### PR DESCRIPTION
**Pull request by dingensundso**
I implemented a pretty quick and dirty fix to get the script working with 2FA (#19). I'm using chipTAN so I am not able to check whether this works with TAN2go or the Banking-App.

### CODE REVIEW

**Comment by jaltek** [comment]
Nope - doesn't seem to work. I'll try to debug this with my account....

```
Traceback (most recent call last):
  File "./dkb.py", line 548, in <module>
    fetcher.login(args.userid, pin)
  File "./dkb.py", line 141, in login
    self.confirm_login()
  File "./dkb.py", line 152, in confirm_login
    form = self._get_tan_input_form()
  File "./dkb.py", line 196, in _get_tan_input_form
    raise RuntimeError("Unable to find tan input form")
RuntimeError: Unable to find tan input form
```

**Comment by hoffie** [comment]
@dingensundso Thanks for working on this! Haven't tried myself yet.
@jaltek Maybe it currently depends on the selected TAN mode (flicker vs. numeric start code)?

**Comment by jaltek** [comment]
Sorry, my fault. I meant it doesn't work with TAN2go.

**Comment by hoffie** [comment]
Just tried it, works perfectly with chipTAN. Thanks a lot @dingensundso!

**Pull request merged**
